export const M3_R4_P4_EVIDENCE_SCHEMA_VERSION =
  'm3-r4-output-root-p4-evidence/v1';
export const M3_R4_P4_ARTIFACT_NAME =
  'm3-r4-p4-fault-security-compatibility-evidence';
export const M3_R4_P4_EXPECTED_HEAD_BRANCH =
  'agent/m3-r4-p4-fault-security-compatibility-9a11bd7';

export const ACCEPTED_M3_R4_P3 = Object.freeze({
  issue: 83,
  pullRequest: 84,
  headSha: '9a11bd749620af23735955fb3c90b034c8e63944',
  naturalWorkflowCount: 22,
  naturalWorkflowSuccess: 22,
  permanentFailedRuns: Object.freeze([31683057327, 31765895829]),
  permanentFailedJobs: Object.freeze([94392726466, 94661607012]),
  artifactId: 9206572282,
  artifactRunId: 31766633684,
  artifactJobId: 94663794366,
  artifactApiDigest:
    'sha256:d65239287215365e008da683297eaed4a8a16db2680619076cb8eb4dfa850d33',
  canonicalEvidenceDigest:
    'a21ba8d33213ee9c08de67f685e63f7a9794d48058d8a343b167b1611fe1576e',
  schemaCatalogDigest:
    '0658defe8fe06f74b17d6caedd33ecf0e711313effa6d172e8797a9876e41d03',
  compatibilityProductDigest:
    '03b2ac5c2c3ad035744426e9ac6a54f800381b6e9e72d9bfc90553f5938a6ac0',
});

export const M3_R4_P4_ACCEPTANCE_PROFILE = Object.freeze({
  implementationStatus: 'ACCEPTANCE_ONLY',
  p3CollectorProductChanged: false,
  p3SchemasChanged: false,
  adversarialAcceptanceComplete: true,
  realFilesystemImplementationEvaluated: true,
  realFilesystemImplementationAuthorized: false,
  realFilesystemCollectorImplemented: false,
  platformCompatibility: 'linux-contract-baseline',
  nodeBaseline: 22,
  nodeCompatibility: 24,
  windowsCompatibilityClaimed: false,
  macosCompatibilityClaimed: false,
});

export const M3_R4_P4_ACCEPTED_THREAT_RESULTS = Object.freeze({
  exactPathAllowlistAccepted: true,
  callerPathAndTraversalRejected: true,
  linkAndSpecialObjectSubstitutionRejected: true,
  unstableObjectAttestationRejected: true,
  staleHandleAndDigestSubstitutionRejected: true,
  parserBoundaryAccepted: true,
  resourceBoundaryAccepted: true,
  failureSanitizationAccepted: true,
  rawDisclosureRejected: true,
  crossNodeProductStable: true,
  effectPrimitiveStaticScanPassed: true,
});

export const M3_R4_P4_LINUX_BOUNDARY = Object.freeze({
  evaluated: true,
  implementationAuthorized: false,
  implementationProofPresent: false,
  platformOwnedPrivateRootRequired: true,
  callerPathRejected: true,
  rootRelativeResolutionRequired: true,
  noFollowRequired: true,
  regularFileOnly: true,
  sameHandleValidationAndReadRequired: true,
  stableObjectIdentityBeforeAfterReadRequired: true,
  boundedReadRequired: true,
  sealedRootRequired: true,
  hostPathPublicDisclosureForbidden: true,
  rawPayloadPersistenceForbidden: true,
  separateAuthorizationRequired: true,
});

export const M3_R4_P4_DECISION = Object.freeze({
  faultSecurityCompatibilityAccepted: true,
  adversarialAcceptanceComplete: true,
  linuxFilesystemBoundaryEvaluated: true,
  linuxFilesystemImplementationAuthorized: false,
  realFilesystemCollectorImplemented: false,
  p3CollectorProductChanged: false,
  nextRequiredSlice: 'M3-R4-G1',
  repositoryBlockers: Object.freeze([]),
});

export const M3_R4_P4_SAFETY_BOUNDARY = Object.freeze({
  realFilesystemPortImplemented: false,
  realFilesystemCollectorImplemented: false,
  realDirectoryCreated: false,
  hostPathResolved: false,
  hostPathIncluded: false,
  callerPathAccepted: false,
  absolutePathAccepted: false,
  realHostFileOpened: false,
  realHostFileRead: false,
  realHostFileWritten: false,
  arbitraryFileReadEnabled: false,
  recursiveDiscoveryPerformed: false,
  symbolicLinkFollowed: false,
  hardLinkTrusted: false,
  specialFileAccepted: false,
  rawPayloadPersisted: false,
  rawPayloadIncludedInEvidence: false,
  sourceBundleMutated: false,
  invocationPlanModified: false,
  nodeProcessAdapterModified: false,
  newProcessPrimitiveAdded: false,
  k6Invoked: false,
  xk6Invoked: false,
  playwrightInvoked: false,
  realExternalProcessStartedInCi: false,
  targetNetworkAccessed: false,
  databaseAccessed: false,
  secretAccessed: false,
  filesystemCredentialAccessed: false,
  rawStdoutCollected: false,
  rawStderrCollected: false,
  numericPidExposed: false,
  workerAdded: false,
  queueAdded: false,
  schedulerAdded: false,
  containerExecutionAdded: false,
  kubernetesExecutionAdded: false,
  remoteExecutionApiAdded: false,
  allureImplemented: false,
  m3R4G1Started: false,
  m4Started: false,
});

export const M3_R4_P4_ARTIFACT_PATHS = Object.freeze([
  'evidence/m3-r4-output-root-p4-evidence.json',
  'schemas/m3-r4-output-root-p4-evidence.schema.json',
  'schemas/m3-r4-output-root-p3-evidence.schema.json',
  'contracts/bounded-file-result-collector.js',
  'contracts/bounded-json-result-payload.js',
  'contracts/bounded-result-collector-contracts.js',
  'contracts/bounded-result-collector-definitions.js',
  'contracts/bounded-result-collector-validation.js',
  'contracts/bounded-result-collector-predecessor.js',
  'tests/m3-r4-p4-fault-security-compatibility.test.js',
  'tests/bounded-file-result-collector-test-helpers.js',
  'scripts/m3-r4-p4/constants.js',
  'scripts/m3-r4-p4/artifact.js',
  'scripts/validate-m3-r4-p4-fault-security-compatibility.js',
  'scripts/validate-m3-r4-p3-bounded-result-collector.js',
  'workflow/m3-r4-p4-fault-security-compatibility-acceptance.yml',
  'metadata/package.json',
  'documents/m3-r4-p4-handoff.md',
  'documents/m3-r4-governed-output-root.md',
  'documents/roadmap.md',
  'documents/m3-r4-p4-acceptance.md',
  'documents/ADR-0036-m3-r4-linux-filesystem-boundary.md',
  'documents/m3-r4-p4-threat-model.md',
  'documents/M3-R4-P4-release.md',
  'documents/m3-r4-p4-index.md',
  'documents/schema-readme.md',
  'logs/m3-r4-p4-focused-node22.tap',
  'logs/m3-r4-p4-focused-node24.tap',
  'logs/m3-r4-p4-adapter-node22.tap',
  'logs/m3-r4-p4-full-node22.tap',
  'logs/m3-r4-p4-repository-validator.log',
  'metadata/manifest.json',
]);
